include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - unnecessary_null_checks
    - unnecessary_brace_in_string_interps
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - sort_pub_dependencies

analyzer:
  exclude:
    - build/**
    - lib/generated/**
  errors:
    missing_return: error
    dead_code: info